//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yesdoctormedicEntities : DbContext
    {
        public yesdoctormedicEntities()
            : base("name=yesdoctormedicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<medico> medico { get; set; }
        public virtual DbSet<agenda> agenda { get; set; }
        public virtual DbSet<especialidade> especialidade { get; set; }
        public virtual DbSet<local> local { get; set; }
    }
}
